backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "static/uploads"
public_folder: "uploads"

collections:
  - name: "staticPage"
    label: "Pages"    
    folder: "content/staticPage"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Position", name: "position", widget: "number"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Seo Title", name: "seotitle", widget: "string"}
      - {label: "Seo Keywords", name: "seokeywords", widget: "string"}
      - {label: "Seo Description", name: "seodescription", widget: "string"}
  - name: "servicePages"
    label: "Services"    
    folder: "content/servicePages"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Position", name: "position", widget: "number"}
      - {label: "Featured Image", name: "image", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Seo Title", name: "seotitle", widget: "string"}
      - {label: "Seo Keywords", name: "seokeywords", widget: "string"}
      - {label: "Seo Description", name: "seodescription", widget: "string"}
  - name: "blog"
    label: "Blog"    
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Featured Image", name: "image", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Seo Title", name: "seotitle", widget: "string"}
      - {label: "Seo Keywords", name: "seokeywords", widget: "string"}
      - {label: "Seo Description", name: "seodescription", widget: "string"}